spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true

jwt:
  secret: ${JWT_SECRET}

app:
  websocket:
    allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS}